spring:
  application:
    name: consumer
  datasource:
    url: jdbc:mysql://localhost:3306/consumer_db?createDatabaseIfNotExist=true
    username: ${usernameDB}
    password: ${passwordDB}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate.ddl-auto: create-drop
    generate-ddl: true
    show-sql: true
    defer-datasource-initialization: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
  sql:
    init:
      mode: always
  kafka:
    bootstrapServers: localhost:9092

server:
  port: 8082